/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sinlov_java_jni_guide_02_datatype_Prompt */

#ifndef _Included_com_sinlov_java_jni_guide_02_datatype_Prompt
#define _Included_com_sinlov_java_jni_guide_02_datatype_Prompt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sinlov_java_jni_guide_02_datatype_Prompt
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sinlov_java_jni_1guide_102_datatype_Prompt_getLine
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
